### PR TITLE
Fix random test hangs when using proxy module

### LINKED ISSUE #298: proxy: waiting for fullmesh doesn't end successfully
In case of using proxies I get the following errors while waiting for fullmesh.

----
## First error

AFAICS, it is reproduced always.

<details>
<summary><b>Reproducer</b></summary>

```lua
local luatest = require('luatest')
local server = require('luatest.server')
local replica_set = require('luatest.replica_set')
local proxy = require('luatest.replica_proxy')

local g = luatest.group('prevote_fail')

g.before_all(function(g)
    g.replica_set = replica_set:new({})

    g.proxy1 = proxy:new{
        client_socket_path = server.build_listen_uri('server1_proxy'),
        server_socket_path = server.build_listen_uri('server1'),
    }
    g.proxy2 = proxy:new{
        client_socket_path = server.build_listen_uri('server2_proxy'),
        server_socket_path = server.build_listen_uri('server2'),
    }
    g.proxy3 = proxy:new{
        client_socket_path = server.build_listen_uri('server3_proxy'),
        server_socket_path = server.build_listen_uri('server3'),
    }

    luatest.assert(g.proxy1:start{force = true}, 'Proxy1 started')
    luatest.assert(g.proxy2:start{force = true}, 'Proxy2 started')
    luatest.assert(g.proxy3:start{force = true}, 'Proxy3 started')

    g.box_cfg = {
        election_mode = 'candidate',
        replication_timeout = 0.01,
        replication = {
            server.build_listen_uri('server1_proxy'),
            server.build_listen_uri('server2_proxy'),
            server.build_listen_uri('server3_proxy'),
        },
    }

    g.server1 = g.replica_set:build_and_add_server{
        alias = 'server1',
        box_cfg = g.box_cfg,
    }

    g.server2 = g.replica_set:build_and_add_server{
        alias = 'server2',
        box_cfg = g.box_cfg,
    }

    g.server3 = g.replica_set:build_and_add_server{
        alias = 'server3',
        box_cfg = g.box_cfg,
    }

    g.replica_set:start()
    g.replica_set:wait_for_fullmesh()
end)

g.after_all(function(g)
    g.replica_set:stop()
end)

g.test_fullmesh_fail = function(g)
  require('fiber').sleep(0.01)
end

```

</details>

```bash
[001] Test failed! Output from reject file ./var/rejects/replication-luatest/dummy.reject:
[001] Tarantool version is 3.0.0-entrypoint-139-gabb172a24
[001] TAP version 13
[001] 1..1
[001] # Started on Tue Apr  4 00:32:21 2023
[001] # Starting group: prevote_fail
[001] not ok 1	prevote_fail.test_fullmesh_fail
[001] #   ...amming/tarantool/test-run/lib/luatest/luatest/server.lua:707: attempt to index field 'upstream' (a nil value)
[001] #   stack traceback:
[001] #   	...amming/tarantool/test/replication-luatest/dummy_test.lua:54: in function <...amming/tarantool/test/replication-luatest/dummy_test.lua:8>
[001] #   	...
[001] #   	[C]: in function 'xpcall'
[001] # Ran 1 tests in 90.644 seconds, 0 succeeded, 1 errored
```

----
## Second error

This one should be ran with `./test-run.py --builddir=../build --vardir=./var $(yes dummy | head -500)`. It's flaky

<details>
<summary><b>Reproducer</b></summary>

```lua
local luatest = require('luatest')
local server = require('luatest.server')
local replica_set = require('luatest.replica_set')
local proxy = require('luatest.replica_proxy')

local g = luatest.group('prevote_fail')

g.before_all(function(g)
    g.replica_set = replica_set:new({})
    g.box_cfg = {
        election_mode = 'candidate',
        replication_timeout = 0.01,
        replication = {
            server.build_listen_uri('server1'),
            server.build_listen_uri('server2'),
            server.build_listen_uri('server3'),
        },
    }

    g.server1 = g.replica_set:build_and_add_server{
        alias = 'server1',
        box_cfg = g.box_cfg,
    }

    g.server2 = g.replica_set:build_and_add_server{
        alias = 'server2',
        box_cfg = g.box_cfg,
    }

    g.proxy3_1 = proxy:new{
        client_socket_path = server.build_listen_uri('server1_proxy'),
        server_socket_path = server.build_listen_uri('server1'),
    }
    g.proxy3_2 = proxy:new{
        client_socket_path = server.build_listen_uri('server2_proxy'),
        server_socket_path = server.build_listen_uri('server2'),
    }

    luatest.assert(g.proxy3_1:start{force = true}, 'Proxy from 3 to 1 started')
    luatest.assert(g.proxy3_2:start{force = true}, 'Proxy from 3 to 2 started')
    g.box_cfg.replication[1] = server.build_listen_uri('server1_proxy')
    g.box_cfg.replication[2] = server.build_listen_uri('server2_proxy')

    g.server3 = g.replica_set:build_and_add_server{
        alias = 'server3',
        box_cfg = g.box_cfg,
    }

    g.replica_set:start()
    g.replica_set:wait_for_fullmesh()
end)

g.after_all(function(g)
    g.replica_set:stop()
end)

g.test_fullmesh_fail = function(g)
  require('fiber').sleep(0.1)
end
```

</details>

```bash

[009] replication-luatest/dummy_test.lua                              [ fail ]
[009] Test failed! Output from reject file ./var/rejects/replication-luatest/dummy.reject:
[009] Tarantool version is 3.0.0-entrypoint-139-gabb172a24
[009] TAP version 13
[009] 1..1
[009] # Started on Tue Apr  4 00:40:49 2023
[009] # Starting group: prevote_fail
[009] not ok 1	prevote_fail.test_fullmesh_fail
[009] #   ...amming/tarantool/test-run/lib/luatest/luatest/server.lua:710: server3: server does not follow upstream
[009] #   expected: "follow"
[009] #   actual: "stopped"
[009] #   stack traceback:
[009] #   	...amming/tarantool/test/replication-luatest/dummy_test.lua:50: in function <...amming/tarantool/test/replication-luatest/dummy_test.lua:8>
```

### PR DESCRIPTION
**Pull request by sergepetrenko**
When one end of the connection is closed for some reason, the proxy should close the other end as well. Otherwise random hangs are possible when a client doesn't notice that the server has closed the socket.

Previously clients never noticed leader disconnect (they only noticed that the heartbeats were missing), and some tests relied on that behaviour while proxy is paused. To preserve it, do not close the sockets while proxy is paused.

Resolves #298

### CODE REVIEW

**Comment by sergepetrenko** [comment]
For some reason the test fails with tarantool 2.8 and lower. I tried to dig into this locally, but proxy is really hard to debug in its current state.
Judging by proxy code, I don't see anything that could stop working on Tarantool 2.8 or earlier compared to 2.10.

Since the proxy was introduced around Tarantool 2.10 and is only used by tests for Tarantool 2.10 and newer, I think it's fine to skip its testing on old tarantool versions. So that's what I did:
https://github.com/tarantool/luatest/blob/1d03cdff9e2a327ac930f419b10cf379c7dc367c/test/proxy_test.lua#L28-L31

File: test/proxy_test.lua [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+        box_cfg = cg.box_cfg,
+    }
+    cg.box_cfg.replication = nil
+    cg.server2 = cg.replica_set:build_and_add_server{
+        alias = 'server2',
+        box_cfg = cg.box_cfg,
+    }
+    cg.proxy = proxy:new{
+        client_socket_path = server.build_listen_uri('server2_proxy'),
+        server_socket_path = server.build_listen_uri('server2'),
```
Comment (ylobankov) [inline test/proxy_test.lua:50]: When you rebase your patch on master, this test will fail. Now you should pass `cg.replica_set.id` to make it work.

**Comment by sergepetrenko** [comment]
The proxy test starts working as expected starting with commit https://github.com/tarantool/tarantool/commit/9cf03555568a728fd4356ed9cce38c26846e4bcc (on 2.11)
which's also cherry-picked to 2.10:
https://github.com/tarantool/tarantool/commit/57ecb6cd90b44012327f22072a6c660a8b516009

The proxy module itself apeared later, in commit https://github.com/tarantool/tarantool/commit/b907e7260920b05886630d1a4e057d865367b403 (it was part of the tarantool repo back then) and wasn't even cherry-picked to 2.10.

So now proxy is operational starting with Tarantool version 2.10.0-29-g57ecb6cd9

File: test/proxy_test.lua (hunk 1 above)
Comment (sergepetrenko) [reply test/proxy_test.lua:50]: Thanks! Rebased on master and fixed the test:
```diff
diff --git a/test/proxy_test.lua b/test/proxy_test.lua
index 73e5fdf..eacff2e 100644
--- a/test/proxy_test.lua
+++ b/test/proxy_test.lua
@@ -29,28 +29,28 @@ g.before_all(function(cg)
     -- Proxy only works on tarantool 2.10+
     t.run_only_if(tarantool_version_ge(2, 10, 0),
                   'Proxy works on Tarantool 2.10+')
-    cg.replica_set = replica_set:new{}
+    cg.rs = replica_set:new{}
     cg.box_cfg = {
         replication_timeout = 0.1,
         replication = {
-            server.build_listen_uri('server2_proxy'),
+            server.build_listen_uri('server2_proxy', cg.rs.id),
         },
     }
-    cg.server1 = cg.replica_set:build_and_add_server{
+    cg.server1 = cg.rs:build_and_add_server{
         alias = 'server1',
         box_cfg = cg.box_cfg,
     }
     cg.box_cfg.replication = nil
-    cg.server2 = cg.replica_set:build_and_add_server{
+    cg.server2 = cg.rs:build_and_add_server{
         alias = 'server2',
         box_cfg = cg.box_cfg,
     }
     cg.proxy = proxy:new{
-        client_socket_path = server.build_listen_uri('server2_proxy'),
-        server_socket_path = server.build_listen_uri('server2'),
+        client_socket_path = server.build_listen_uri('server2_proxy', cg.rs.id),
+        server_socket_path = server.build_listen_uri('server2', cg.rs.id),
     }
     t.assert(cg.proxy:start{force = true}, 'Proxy is started')
-    cg.replica_set:start{}
+    cg.rs:start{}
 end)
 
 g.test_server_disconnect_is_noticed = function(cg)
@@ -78,5 +78,5 @@ g.test_server_disconnect_is_noticed = function(cg)
 end
 
 g.after_all(function(cg)
-    cg.replica_set:drop()
+    cg.rs:drop()
 end)
```

**Review by ochaplashkin — APPROVED** [review]
LGTM

**Review by ylobankov — APPROVED** [review]
LGTM
