### PR TITLE
Accept table as net_box_uri

### LINKED ISSUE #341: URI length is checked instead of unix socket path length
For example we have test `app-luatest/example_test.lua` on Tarantool-Enterprise:
```Lua
local server = require('luatest.server')
local t = require('luatest')

local g = t.group()

g.test_too_long_uri = function()
    local net_box_uri = "guest@unix/:/tmp/temp?transport=ssl&" ..
                        "ssl_cert_file=/home/mergen/work/ee/test/enterprise-luatest/ssl_cert/client.crt&" ..
                        "ssl_key_file=/home/mergen/work/ee/test/enterprise-luatest/ssl_cert/client.key"
    t.assert_equals(#net_box_uri, 192)
    g.server = server:new{
        alias = 'master',
        net_box_uri = net_box_uri,
    }
    g.server:start()
    g.server:drop()
end
```

When we run it, we will get an error:
```
======================================================================================
WORKR TEST                                            PARAMS          RESULT
---------------------------------------------------------------------------------
[001] app-luatest/example_test.lua                                    [ fail ]
[001] Test failed! Output from reject file /tmp/t/rejects/app-luatest/example.reject:
[001] Tarantool version is 3.0.0-beta1-53-g59b817ef8
[001] TAP version 13
[001] 1..1
[001] # Started on Tue Dec 12 14:40:48 2023
[001] # Starting group: app-luatest.example
[001] not ok 1	app-luatest.example.test_too_long_uri
[001] #   .../mergen/work/dev/test-run/lib/luatest/luatest/server.lua:165: Net box URI must be <= max Unix domain socket path length (107 chars)
[001] #   stack traceback:
[001] #   	/home/mergen/work/dev/test/app-luatest/example_test.lua:11: in function 'app-luatest.example.test_too_long_uri'
[001] #   	...
[001] #   	[C]: in function 'xpcall'
[001] # Ran 1 tests in 0.003 seconds, 0 succeeded, 1 errored
[001] 
[001] [test-run server "luatest_server"] The log file /tmp/t/001_app-luatest/example_test.log has zero size
[Main process] Got failed test; gently terminate all workers...
[001] Worker "001_app-luatest" got failed test; stopping the server...
---------------------------------------------------------------------------------
```

The Unix socket path here is `/tmp/temp` and its length is 9.

### LINKED ISSUE #342: Allow to set table as net_box_uri
Currently, the net_box_uri argument only accepts a string. However, it is legal to use a table to set up a listen, if the table can be parsed using `require('uri').parse()`. Allowing table as net_box_uri makes it easier to use params, such as SSL params.

### PR DESCRIPTION
**Pull request by ImeevMA**
Prior to this patch-set, box.cfg.listen was only set to string or number. Because of this, it was not possible to use the table as net_box_uri when creating the server. This patch-set allows the table to be used as net_box_uri. Also, now length of unix socket path is checked instead of length of whole URI. However, to support backward compatibility, the table representation of net_box_uri is converted to string.

Closes #341
Closes #342

### CODE REVIEW

File: test/server_test.lua [hunk 1]
```diff
@@ -296,6 +296,32 @@ g.test_max_unix_socket_path_exceeded = function()
...
+    print(net_box_uri)
+    local s = Server:new({
+        command = command,
+        workdir = workdir,
+        net_box_uri = net_box_uri,
+        http_port = 0, -- unused
+    })
+    s:start()
+    t.helpers.retrying({}, function() s:connect_net_box() end)
+    t.assert_equals(s:exec(function() return box.cfg.listen end), net_box_uri)
```
Comment (Totktonada) [inline test/server_test.lua:321]: Nit: I would compare host:port without login:password, because it is OK if luatest will strip login:password from net_box_uri to pass to box.cfg.listen.

File: luatest/server.lua [hunk 2]
```diff
@@ -226,9 +227,12 @@ function Server:build_env()
     local res = {
         TARANTOOL_WORKDIR = self.workdir,
         TARANTOOL_HTTP_PORT = self.http_port,
-        TARANTOOL_LISTEN = self.net_box_port or self.net_box_uri,
         TARANTOOL_ALIAS = self.alias,
     }
+    local listen = self.net_box_port or self.net_box_uri
+    if listen ~= nil then
+        res.TARANTOOL_LISTEN = json.encode(listen)
+    end
```
Comment (Totktonada) [inline luatest/server.lua:235]: Here we break compatibility with commands other than the default (server_instance.lua).

File: test/server_test.lua [hunk 3]
```diff
@@ -296,6 +296,32 @@ g.test_max_unix_socket_path_exceeded = function()
...
+    local workdir = fio.pathjoin(datadir, 'unix_socket')
+    fio.mktree(workdir)
+    local workdir_len = string.len(workdir)
+    local socket_name_len = max_unix_socket_path[system] + 1 - workdir_len
+    local socket_name = string.format('test_socket%s.sock',
+                                      string.rep('t', socket_name_len - 18))
+    local socket_path = fio.pathjoin(workdir, socket_name)
+    t.assert_equals(string.len(socket_path), max_unix_socket_path[system])
+    local net_box_uri = 'guest@unix/:' .. socket_path .. '?three=1&four=2'
+    print(net_box_uri)
```
[the remark this answers is not in the document]
Comment (ImeevMA) [reply test/server_test.lua]: True, removed.

File: luatest/server.lua (hunk 2 above)
Comment (ImeevMA) [reply luatest/server.lua]: True. Now table is converted to string using `uri.format(uri.parse(table), true)`.

**Review by Totktonada — APPROVED** [review]
Thank you!

**Review by ochaplashkin — APPROVED** [review]
