### PR TITLE
Check test path exists before running tests

### LINKED ISSUE #175: luatest tries to run tests in non existent file
Imagine we have non-existent file:
```
sergeyb@pony:~/sources/MRG/crud$ stat test/integration/ddl_sharding_key_test1.lua
stat: cannot stat 'test/integration/ddl_sharding_key_test1.lua': No such file or directory
```

luatest will try to run tests in this file and will show a huge error:
```
sergeyb@pony:~/sources/MRG/crud$ ./.rocks/bin/luatest -v test/integration/ddl_sharding_key_test1.lua
"tuple.keydef" module is not found. Built-in "key_def" is used                                                                                                
"tuple.merger" module is used                                                                                                                                 
...urces/MRG/crud/.rocks/share/tarantool/luatest/loader.lua:43: module 'test.integration.ddl_sharding_key_test1' not found:No LuaRocks module found for test.i
ntegration.ddl_sharding_key_test1    
...
stack traceback:
        ...rces/MRG/crud/.rocks/share/tarantool/luatest/capture.lua:144: in function <...rces/MRG/crud/.rocks/share/tarantool/luatest/capture.lua:138>
        [C]: in function 'require'
        ...urces/MRG/crud/.rocks/share/tarantool/luatest/loader.lua:43: in function 'load_tests'
        ...urces/MRG/crud/.rocks/share/tarantool/luatest/runner.lua:248: in function <...urces/MRG/crud/.rocks/share/tarantool/luatest/runner.lua:245>
        [C]: in function 'xpcall'
        ...ources/MRG/crud/.rocks/share/tarantool/luatest/utils.lua:37: in function 'bootstrap'
        ...urces/MRG/crud/.rocks/share/tarantool/luatest/runner.lua:254: in function <...urces/MRG/crud/.rocks/share/tarantool/luatest/runner.lua:253>
        [C]: in function 'xpcall'
        ...es/MRG/crud/.rocks/share/tarantool/luatest/capturing.lua:74: in function <...es/MRG/crud/.rocks/share/tarantool/luatest/capturing.lua:72>
        [C]: in function 'xpcall'
        ...urces/MRG/crud/.rocks/share/tarantool/luatest/runner.lua:49: in function 'fn'
        ...crud/.rocks/share/tarantool/luatest/sandboxed_runner.lua:14: in function 'run'
        ...G/crud/.rocks/share/tarantool/luatest/cli_entrypoint.lua:4: in function <...G/crud/.rocks/share/tarantool/luatest/cli_entrypoint.lua:3>
        ...d/.rocks/share/tarantool/rocks/luatest/scm-1/bin/luatest:3: in main chunk
```

I believe luatest can handle this and make a sanity check for a file that passed by user.

### PR DESCRIPTION
**Pull request by ylobankov**
Closes #175

### CODE REVIEW

**Review by ligurio — COMMENTED** [review]
```sh
sergeyb@pony:~/sources/MRG/luatest$ ./.rocks/bin/luatest -v test/
Running with --shuffle group:4487                                                                                                       
Started on Tue Dec 21 13:01:01 2021                                                                                                     
    assertions.test_assert_equals_for_cdata ... (0.005s) Ok                                                                             
    assertions.test_custom_errors ... (0.051s) Ok

...
```

How it should work?

Path without trailing slash:
```
sergeyb@pony:~/sources/MRG/luatest$ ./.rocks/bin/luatest -v test                                                                        
/home/sergeyb/sources/MRG/luatest/luatest/runner.lua:430: Invalid test name: test
stack traceback:                                                                                                                        
        /home/sergeyb/sources/MRG/luatest/luatest/capturing.lua:81: in function </home/sergeyb/sources/MRG/luatest/luatest/capturing.lua
:74>                                                                                                                                            [C]: in function 'assert'  
...
```

non-existed path:
```
~/sources/MRG/luatest$ ./.rocks/bin/luatest -v test1
/home/sergeyb/sources/MRG/luatest/luatest/runner.lua:430: Invalid test name: test1
stack traceback:
        /home/sergeyb/sources/MRG/luatest/luatest/capturing.lua:81: in function </home/sergeyb/sources/MRG/luatest/luatest/capturing.lua:74>
...
```

File: luatest/runner.lua [hunk 1]
```diff
@@ -154,8 +155,11 @@ function Runner.parse_cmd_line(args)
         elseif arg:sub(1,1) == '-' then
             error('Unknown option: ' .. arg)
         elseif arg:find('/') then
```
Comment (ligurio) [inline luatest/runner.lua:157]: For me, it is not clear why trailing slash is mandatory for paths. Probably we should use `fio.path.exists(arg)` to decide whether it is a path or not.

**Comment by ylobankov** [comment]
> ```shell
> sergeyb@pony:~/sources/MRG/luatest$ ./.rocks/bin/luatest -v test/
> Running with --shuffle group:4487                                                                                                       
> Started on Tue Dec 21 13:01:01 2021                                                                                                     
>     assertions.test_assert_equals_for_cdata ... (0.005s) Ok                                                                             
>     assertions.test_custom_errors ... (0.051s) Ok
> 
> ...
> ```
> 
> How it should work?
> 
> Path without trailing slash:
> 
> ```
> sergeyb@pony:~/sources/MRG/luatest$ ./.rocks/bin/luatest -v test                                                                        
> /home/sergeyb/sources/MRG/luatest/luatest/runner.lua:430: Invalid test name: test
> stack traceback:                                                                                                                        
>         /home/sergeyb/sources/MRG/luatest/luatest/capturing.lua:81: in function </home/sergeyb/sources/MRG/luatest/luatest/capturing.lua
> :74>                                                                                                                                            [C]: in function 'assert'  
> ...
> ```
> 
> non-existed path:
> 
> ```
> ~/sources/MRG/luatest$ ./.rocks/bin/luatest -v test1
> /home/sergeyb/sources/MRG/luatest/luatest/runner.lua:430: Invalid test name: test1
> stack traceback:
>         /home/sergeyb/sources/MRG/luatest/luatest/capturing.lua:81: in function </home/sergeyb/sources/MRG/luatest/luatest/capturing.lua:74>
> ...
> ```

If you provide just `test` (without the slash), luatest treats it as a group name. That is luatest tries to run all tests from `test` group. From luatest help command:
```
Usage: luatest [options] [files or dirs...] [testname1 ...]
Options:
  -h, --help:             Print this help
  --version:              Print version information
  -v, --verbose:          Increase verbosity
  -q, --quiet:            Set verbosity to minimum
  ...
  test_name, ...:         Tests to run in the form of group_name or group_name.test_name
```
For now to run tests from a particular folder you should specify a path with `/`.

File: luatest/runner.lua (hunk 1 above)
Comment (ylobankov) [reply luatest/runner.lua:157]: The trailing slash is not mandatory, a path can be like that `./path`. If you provide just `foo` (without the slash), luatest treats it as a group name. That is luatest will try to run all tests from `foo` group.

Comment (Totktonada) [reply luatest/runner.lua:157]: Or `fio.stat(<...>)` to distinguish a regular file from a directory. It would have more expected behaviour, I guess.

However it looks as out of #175 scope.

**Review by Totktonada — APPROVED** [review]
As solution for given problem it looks ok.

However I'm agree with Sergey that `/` search within a string is not quite intuitive as the differentiator between file/dir name and group/test name.

File: luatest/runner.lua (hunk 1 above)
Comment (ylobankov) [reply luatest/runner.lua:157]: Guys, I am OK with your suggestions, but it is really out of the scope of the issue that is going to be fixed by this PR. Let's continue this discussion in a separate issue.
