### PR TITLE
Fix server start issue when coverage is enabled

### LINKED ISSUE #274: luatest --coverage fails
command `.rocks/bin/luatest --coverage -v test/` always fails, while `.rocks/bin/luatest -v test/` works fine since [this commit](https://github.com/tarantool/luatest/commit/e75b6f45d7ed2f1eaf133db6862fd9f2b6890ccd). You can see error below
```
1) integration_api.test_sample
/luat/.rocks/share/tarantool/luatest/server.lua:411: connect, called on fd 13, aka 127.0.0.1:36972: Connection refused
stack traceback:
        ....rocks/share/tarantool/cartridge/test-helpers/server.lua:116: in function 'connect_net_box'
        ....rocks/share/tarantool/cartridge/test-helpers/server.lua:126: in function 'retrying'
        ....rocks/share/tarantool/cartridge/test-helpers/server.lua:125: in function 'start'
        ...rocks/share/tarantool/cartridge/test-helpers/cluster.lua:265: in function 'start'
        /luat/test/integration/api_test.lua:9: in function 'integration_api.before_all'
        ...
        [C]: in function 'xpcall'

Captured stdout:
api | LuajitError: /usr/bin/tarantool:1: unexpected symbol near 'char(127)'
api | fatal error, exiting the event loop
```

How to reproduce: 
1. create empty app
`cartridge create`
2. add luacov into cartridge.pre-build
`tarantoolctl rocks install luacov`
3. add luatest
there are two ways to do it:
* add 'luatest' as dependence to `myapp-scm-1.rockspec`
* add luatest git repo to project and then paste `tarantoolctl rocks make --chdir ./luatest/` to cartridge.pre-build
4. build app and run test
`cartridge build`
`.rocks/bin/luatest --coverage -v test/`

I want to notice that currently [Process:start](https://github.com/tarantool/luatest/blob/e75b6f45d7ed2f1eaf133db6862fd9f2b6890ccd/luatest/server.lua#L249) takes as `args` `["\/usr\/bin\/tarantool","-l","luatest.coverage","\/luat\/init.lua"]`. I believe that `args` shoud be `["-l","luatest.coverage","\/luat\/init.lua"]`

### PR DESCRIPTION
**Pull request by ylobankov**
Fix the following error:

    LuajitError: /usr/bin/tarantool:1: unexpected symbol near 'char(127)'
    fatal error, exiting the event loop

Fixes #274

### CODE REVIEW

File: luatest/server.lua [hunk 1]
```diff
@@ -227,27 +230,32 @@ function Server:start(opts)
 
     self:initialize()
 
+    local command = self.command
+    local args = table.copy(self.args)
     local env = table.copy(os.environ())
+
+    if not command:endswith('/tarantool') then
+        -- When luatest is installed as a rock, the internal server_instance.lua
```
Comment (NickVolynkin) [inline luatest/server.lua:238]: good description!

**Review by NickVolynkin — APPROVED** [review]

**Review by slavakirichenko — APPROVED** [review]
